# Generated by Django 3.2.9 on 2022-01-27 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caracteristique',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='identite',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='caracteristique',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='identite',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='updated_at',
            new_name='update_at',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='updated_at',
            new_name='update_at',
        ),
    ]
